### PR TITLE
Added advanced search and load from disk at init

### PR DESCRIPTION
**Pull request by luiscarrasco**
Added advanced search with multiple fields. Proposed search would be more RESTful with no verb in the URI.

Instead of:
* users/search?field=name&equal=Luis
you do:
* users?name=Luis

In the future if you would like to do comparisons you could do either of
* users?age=gt;15
* users?age=>15

I also added the capability to restore values from disk without the need executing getElement first. I found it quirky that in order to search for a value yo would have to get it first. Unless I am missing something in the design or intent of this project then I think it is necessary to be able to search for values after the system is restored from a crash.

### CODE REVIEW

**Comment by luiscarrasco** [comment]
The failed test is due to the swapping of an element in the LRU. This I found strange since the test seemed to pass depending on the weather and time of day (hehe). I know this might have gotten messed up by the reading of documents at the beginning. Did you ever run into this test failing? Tests might need to be more aware of how other threads complete their jobs.

**Comment by Fersca** [comment]
Hi Luis @luiscarrasco ,
I see only one issue with the approach that you have used.
The problem if that if you have more json's in disk than your available RAM, you would not be able to upload al the content. It you get out of memory, only the keys are going to be stored in memory and the contend will remain in disk.
I will accept the pull request but I will try to add the following functionality:
- If we get out of memory, only the keys are going to be stored in memory.
- When we were searching, if we get only a key from memory, we can read the json compare it, keep it if it's ok with the comparison and let it in disk.
- That would cause a great performance degradation but I cant imagine another solution if you have more  json content than memory.

Do you have another idea?

**Comment by luiscarrasco** [comment]
Not at the moment, no. I would really prefer to have an indexing scheme in
place, but for now this gives me the functionality that I want, of course
at a performance cost if you have more data than cache allocated. I can
look more into this next week.

**Comment by Fersca** [comment]
@luiscarrasco I updated the comment before, I think that it will be fixed only if you can check if the node is swapped and if it is, read the content from disk, compare and not save it to memory.
Let me know if you cant add this fix and I could add this next week.

**Comment by luiscarrasco** [comment]
@Fersca, sorry for the late response. I was looking into adding the swapping. When I ran the tests it encountered an element in the cc map with an ID that I did not add but it is not marked as deleted nor is it swapped. I am looking into this.

**Comment by Fersca** [comment]
@luiscarrasco I merged the pull request because it passed all the tests. I test it on my computer and it worked, maybe thare is an element in the list for a previous test.
If you can fix it, great, if not I will add the functionality later :)

**Pull request merged**
